export const PRODUCT_DETAIL='PRODUCT_DETAIL';
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL='PRODUCT_DETAIL_FAIL';


export const BANNER_LIST='BANNER_LIST';
export const BANNER_LIST_SUCCESS='BANNER_LIST_SUCCESS';
export const BANNER_LIST_FAIL='BANNER_LIST_FAIL';


export const CATEGORY_LIST='CATEGORY_LIST';
export const CATEGORY_LIST_SUCCESS='CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL='CATEGORY_LIST_FAIL';

export const CARCATE_LIST='CARCATE_LIST';
export const CARCATE_LIST_SUCCESS='CARCATE_LIST_SUCCESS';
export const CARCATE_LIST_FAIL='CARCATE_LIST_FAIL';


export const SHOW_MESSAGE = 'SHOW_MESSAGE';