export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL';

export const SEARCH_LIST = 'SEARCH_LIST';
export const SEARCH_LIST_SUCCESS = 'SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAIL = 'SEARCH_LIST_FAIL';

export const HOME_LIST = 'HOME_LIST';
export const HOME_LIST_SUCCESS = 'HOME_LIST_SUCCESS';
export const HOME_LIST_FAIL = 'HOME_LIST_FAIL';

export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_HOT = 'CATEGORY_HOT';
export const CATEGORY_HOT_SUCCESS = 'CATEGORY_HOT_SUCCESS';
export const CATEGORY_HOT_FAIL = 'CATEGORY_HOT_FAIL';


export const CITY_LIST = 'CITY_LIST';
export const CITY_LIST_SUCCESS = 'CITY_LIST_SUCCESS';
export const CITY_LIST_FAIL = 'CITY_LIST_FAIL';


export const CARCATE_LIST = 'CARCATE_LIST';
export const CARCATE_LIST_SUCCESS = 'CARCATE_LIST_SUCCESS';
export const CARCATE_LIST_FAIL = 'CARCATE_LIST_FAIL';

export const GET_MY_CAR_LIST = 'GET_MY_CAR_LIST';
export const GET_MY_CAR_LIST_SUCCESS = 'GET_MY_CAR_LIST_SUCCESS';
export const GET_MY_CAR_LIST_FAIL = 'GET_MY_CAR_LIST_FAIL';

export const SELECT_CAR = 'SELECT_CAR';
export const SELECT_CAR_SUCCESS = 'SELECT_CAR_SUCCESS';
export const SELECT_CAR_FAIL = 'SELECT_CAR_FAIL';

export const DELETE_CAR = 'DELETE_CAR';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const DELETE_CAR_FAIL = 'DELETE_CAR_FAIL';

export const SET_DEFAULT_CAR = 'SET_DEFAULT_CAR';
export const SET_DEFAULT_CAR_SUCCESS = 'SET_DEFAULT_CAR_SUCCESS';
export const SET_DEFAULT_CAR_FAIL = 'SET_DEFAULT_CAR_FAIL';


export const ADDRESS_LIST = 'ADDRESS_LIST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';

export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const SET_DEFAULT_ADDRESS_SUCCESS = 'SET_DEFAULT_ADDRESS_SUCCESS';
export const SET_DEFAULT_ADDRESS_FAIL = 'SET_DEFAULT_ADDRESS_FAIL';

export const SHOP_CART_LIST = 'SHOP_CART_LIST';
export const SHOP_CART_LIST_SUCCESS = 'SHOP_CART_LIST_SUCCESS';
export const SHOP_CART_LIST_FAIL = 'SHOP_CART_LIST_FAIL';

export const ADD_SHOP_CART = 'ADD_SHOP_CART';
export const ADD_SHOP_CART_SUCCESS = 'ADD_SHOP_CART_SUCCESS';
export const ADD_SHOP_CART_FAIL = 'ADD_SHOP_CART_FAIL';

export const DELETE_SHOP_CART = 'DELETE_SHOP_CART';
export const DELETE_SHOP_CART_SUCCESS = 'DELETE_SHOP_CART_SUCCESS';
export const DELETE_SHOP_CART_FAIL = 'DELETE_SHOP_CART_FAIL';

export const UPDATE_SHOP_CART = 'UPDATE_SHOP_CART';
export const UPDATE_SHOP_CART_SUCCESS = 'UPDATE_SHOP_CART_SUCCESS';
export const UPDATE_SHOP_CART_FAIL = 'UPDATE_SHOP_CART_FAIL';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';