export {default as Splash} from './Splash'
export {default as Main} from './Main'
export {default as Home} from './Home'
export {default as SelectCar} from './SelectCar'
export {default as List} from './List'
export {default as Search} from './Search'
export {default as Product} from './Product'